# Generated by Django 5.1.7 on 2025-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=255)),
                ('start_stop', models.CharField(max_length=255)),
                ('destination_stop', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('reach_time', models.TimeField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_upi', models.CharField(max_length=255)),
            ],
        ),
    ]
